name: Run K6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install K6
        run: |
          # Add K6's GPG key and APT repository
          curl -fsSL https://dl.k6.io/deb/k6.asc | sudo tee /etc/apt/trusted.gpg.d/k6.asc
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          
          # Update the package list and install K6
          sudo apt update
          sudo apt install k6 -y

      - name: Run K6 Load Test
        run: k6 run test-script.js

      - name: Upload K6 Test Results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results/
