name: Run K6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install K6 (Direct Binary Download)
        run: |
          # Download the latest K6 binary (v0.45.1 or newer)
          wget https://github.com/grafana/k6/releases/download/v0.45.1/k6-linux-amd64-v0.45.1.tar.gz
          
          # Extract the archive
          tar -xvzf k6-linux-amd64-v0.45.1.tar.gz
          
          # Move the binary to a directory in PATH
          sudo mv k6-linux-amd64-v0.45.1/k6 /usr/local/bin/k6

      - name: Run K6 Load Test
        run: k6 run test-script.js

      - name: Upload K6 Test Results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results/
